### DISCUSSION TITLE
How to best visualize percent values with discrete thresholds

### DISCUSSION THREAD

**Discussion by danieldides** [flant/grafana-statusmap#191] [Q&A]
Hey, thanks for the great plugin.

We're trying to use the plugin to create an at-a-glance visualization of server health (CPU, memory, etc). These metrics are being aggregated in Prometheus as "gauge" values and return a percent-value between 0 and 1. I'm trying to determine the best way using Prometheus or this plugin to manipulate the data in such a way that we can set discrete thresholds within which we can assign specific colors and states.

For example, I would like to be able to assign `Green` to a CPU value from <0.5, `Yellow` to a returned value of 0.5 - 0.75, and `Red` for anything that returns over 0.75. 

Right now, I think my solution is suboptimal. I've created two rules in Prometheus:

```yaml

  groups:
  - name: stackdriver:cpu
    rules: 
    - record: stackdriver:cpu:high
      expr: stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization > bool 0.5
    - record: stackdriver:cpu:critical
      expr: stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization > bool 0.75
```

and then in Grafana, I've created this query: `stackdriver:cpu:high + stackdriver:cpu:critical` and mapped in the plugin 0 to green, 1 to yellow, and 2 to red.

If anyone has any recommendations on a more graceful way to handle this, I'd love to hear it!

**Comment by diafour** [comment]
Hello!
One of the possible solution is that you record a sum:

```yaml
groups:
  - name: stackdriver:cpu
    rules: 
    - record: stackdriver:cpu:thresholds
      expr: |
        (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization > bool 0.5)
        +
        (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization > bool 0.75)
```

And then use `max_over_time` as suggested in README to get the most critical value for one bucket:

```
max_over_time(stackdriver:cpu:thresholds[$__interval])
```
